path:
   goal10:
     x: -1.6
     y: 2.0
   goal11:
     x: -0.875
     y: 2.0
   goal12:
     x: -0.15
     y: 2.0
   goal13:
     x: -0.15
     y: 1.08
   goal14:
     x: -0.875
     y: 1.08
   goal15:
     x: -1.6
     y: 1.08